# Generated by Django 3.1.6 on 2021-02-18 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_TC',
            fields=[
                ('branch_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_kind', models.CharField(max_length=30)),
                ('established', models.DateField(blank=True)),
                ('capacity', models.IntegerField(blank=True)),
                ('postcode', models.BigIntegerField()),
                ('province', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('district', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('alley', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('med_sys_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('specialist', models.CharField(blank=True, max_length=30)),
                ('hospital_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('national_ID', models.BigIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True)),
                ('hiring_date', models.DateField(blank=True)),
                ('work_place', models.CharField(blank=True, max_length=60)),
                ('post', models.CharField(max_length=30)),
                ('phone_num', models.IntegerField(blank=True)),
                ('province', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('district', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('alley', models.CharField(blank=True, max_length=30)),
                ('blo_branch_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employees1', to='new_app.blood_tc')),
                ('branch_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='new_app.blood_tc')),
            ],
        ),
        migrations.CreateModel(
            name='Lab_technician',
            fields=[
                ('lab_tech_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lab_techs', to='new_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('donator_num', models.IntegerField(primary_key=True, serialize=False)),
                ('national_ID', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('blood_type', models.CharField(max_length=30)),
                ('deseas_rec', models.CharField(max_length=100)),
                ('vital_signs', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('wieght', models.IntegerField()),
                ('phone_num', models.IntegerField()),
                ('postcode', models.IntegerField()),
                ('consent', models.BooleanField()),
                ('province', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('district', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('alley', models.CharField(blank=True, max_length=30)),
                ('employee_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='don_em', to='new_app.employee')),
                ('med_sys_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='don_doc', to='new_app.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='employee_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='new_app.employee'),
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('bar_code', models.IntegerField(primary_key=True, serialize=False)),
                ('blood_type', models.CharField(max_length=20)),
                ('donation_date', models.DateField()),
                ('hemoglobin_lvl', models.IntegerField()),
                ('health_status', models.CharField(max_length=100)),
                ('branch_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blood_btc', to='new_app.blood_tc')),
                ('donator_num', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blood_don', to='new_app.donator')),
                ('employee_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blood_em', to='new_app.employee')),
                ('lab_employee_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blood_lab', to='new_app.lab_technician')),
                ('lab_tech_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blood_l', to='new_app.lab_technician')),
                ('med_sys_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blood_doc', to='new_app.doctor')),
            ],
        ),
    ]
